Repository puppetlabs/puppetlabs-firewall, pull requests merged in 2018-12, with the labels that each got.

#796 (MODULES-6340) - Address failure when name begins with 9XXX
  README.markdown
  lib/puppet/provider/firewall/iptables.rb
  spec/acceptance/firewall_spec.rb
Labels: bugfix

#798 (MODULES-8143) - Add SLES 15 support
  metadata.json
Labels: feature

#799 pdksync - pdksync_heads/master-0-gbf720df
  .gitattributes
  .pdkignore
  .puppet-lint.rc
  .travis.yml
  Rakefile
  metadata.json
  spec/default_facts.yml
  spec/spec_helper.rb
Labels: maintenance

#801 pdksync - (FM-7655) Fix rubygems-update for ruby < 2.3
  .travis.yml
  metadata.json
Labels: bugfix
