Repository puppetlabs/puppetlabs-firewall, pull requests merged in 2019-11, with the labels that each got.

#869 pdksync - (FM-8634) ensure encrypted communication for fixtures
  .fixtures.yml
Labels: maintenance

#871 pdksync - FM-8499 - remove ubuntu14 support
  metadata.json
  provision.yaml
Labels: backwards-incompatible

#873 (FM-8673) - Support added for CentOS 8
  metadata.json
  provision.yaml
Labels: feature

#874 Change - Avoid puppet failures on windows nodes
  manifests/init.pp
Labels: bugfix

#876 Add support for Debian Unstable
  lib/facter/iptables_persistent_version.rb
  manifests/params.pp
  spec/unit/classes/firewall_linux_debian_spec.rb
Labels: feature

#879 (MODULES-10120) enable simplecov; update to PDK 1.14.1; minor cleanups
  .gitignore
  .pdkignore
  .project
  .sync.yml
  .travis.yml
  Gemfile
  metadata.json
Labels: maintenance
