Repository puppetlabs/puppetlabs-firewall, pull requests merged in 2019-04, with the labels that each got.

#832 (maint) Convert resource_cmd_spec to rspec-mock
  spec/acceptance/resource_cmd_spec.rb
Labels: maintenance

#833 (MODULES-8842) Fix ipvs not idempotent
  README.markdown
  lib/puppet/provider/firewall/iptables.rb
  lib/puppet/type/firewall.rb
  spec/acceptance/firewall_attributes_happy_path_spec.rb
Labels: bugfix

#834 (MODULES-8855) Move ipvs test to exception spec
  spec/acceptance/firewall_attributes_exceptions_spec.rb
  spec/acceptance/firewall_attributes_happy_path_spec.rb
Labels: bugfix

#836 (MODULES-8849) Release prep 1.15.3
  CHANGELOG.md
  metadata.json
Labels: maintenance

#837 Release mergeback 1.15.3
  CHANGELOG.md
  metadata.json
Labels: maintenance

#841 pdksync - (MODULES-8444) - Raise lower Puppet bound
  metadata.json
Labels: backwards-incompatible

#838 (FM-7903) - Implement Puppet Strings
  README.markdown
  REFERENCE.md
  lib/puppet/type/firewall.rb
  lib/puppet/type/firewallchain.rb
  manifests/init.pp
  manifests/linux.pp
  manifests/linux/archlinux.pp
  manifests/linux/debian.pp
  manifests/linux/gentoo.pp
  manifests/linux/redhat.pp
  manifests/params.pp
Labels: feature

#842 pdksync - (maint) Update pdk-template to f778803
  .gitignore
  .pdkignore
  .puppet-lint.rc
  .travis.yml
  metadata.json
Labels: maintenance
