Repository puppetlabs/puppetlabs-firewall, pull requests merged in 2021-09, with the labels that each got.

#1010 Fix "undefined method `gsub' for nil:NilClass" when changing existing rule UID from absent to any present
  lib/puppet/type/firewall.rb
Labels: bugfix

#1011 pdksync: changelog_max_issues set to 500
  .github/workflows/auto_release.yml
  .sync.yml
  Rakefile
  metadata.json
Labels: maintenance

#1014 Add carp protocol to :proto property
  lib/puppet/type/firewall.rb
  spec/unit/puppet/type/firewall_spec.rb
Labels: bugfix

#1015 pdksync - (IAC-1598) - Remove Support for Debian 8
  metadata.json
Labels: bugfix

#1017 pdksync - (IAC-1751) - Add Support for Rocky 8
  metadata.json
Labels: feature
