Repository puppetlabs/puppetlabs-firewall, pull requests merged in 2021-07, with the labels that each got.

#997 sles-15: mac_source is downcased by iptables
  lib/puppet/type/firewall.rb
  spec/acceptance/firewall_attributes_exceptions_spec.rb
Labels: bugfix

#996 fix: parsing random_fully in ip6tables
  lib/puppet/provider/firewall/ip6tables.rb
  spec/fixtures/ip6tables/conversion_hash.rb
Labels: bugfix

#999 Update changelog_since_tag
  .github/workflows/spec.yml
  .sync.yml
  Rakefile
  metadata.json
Labels: maintenance

#998 add compatibility with Rocky Linux
  lib/puppet/util/firewall.rb
  manifests/linux.pp
Labels: feature

#1001 pdksync - (maint) - Updating Contribution Guidelines
  CONTRIBUTING.md
Labels: maintenance

#1002 (MODULES-11138) - Fix mac_source Facter.fact().value() issue with Facter 3
  lib/puppet/type/firewall.rb
Labels: bugfix
