Repository puppetlabs/puppetlabs-firewall, pull requests merged in 2022-11, with the labels that each got.

#1084 (CONT-256) Removing outdated code
  lib/facter/iptables_persistent_version.rb
  lib/puppet/type/firewall.rb
  manifests/linux/debian.pp
  manifests/linux/redhat.pp
  manifests/params.pp
  spec/unit/classes/firewall_linux_debian_spec.rb
  spec/unit/classes/firewall_linux_redhat_spec.rb
  spec/unit/classes/firewall_linux_spec.rb
  spec/unit/puppet/provider/ip6tables_spec.rb
  spec/unit/puppet/provider/iptables_chain_spec.rb
  spec/unit/puppet/provider/iptables_spec.rb
Labels: backwards-incompatible

#1090 Revert "(CONT-5) Raising minimum required puppet version"
  metadata.json
Labels: maintenance

#1059 add support for using rpfilter in rules
  lib/puppet/provider/firewall/iptables.rb
  lib/puppet/type/firewall.rb
  spec/acceptance/firewall_attributes_happy_path_spec.rb
Labels: feature, community
