Repository puppetlabs/puppetlabs-firewall, pull requests merged in 2022-10, with the labels that each got.

#1058 (GH-1055) Fix for `--random-fully`
  lib/puppet/provider/firewall/iptables.rb
Labels: bugfix

#1023 fix service port number lookup to use protocol
  lib/puppet/type/firewall.rb
  spec/unit/puppet/provider/iptables_spec.rb
Labels: community

#1075 pdksync - (CONT-130) - Dropping Support for Debian 9
  metadata.json
Labels: bugfix, hacktoberfest

#1078 pdksync - (CONT-189) Remove support for RedHat6 / OracleLinux6 / Scientific6
  metadata.json
Labels: bugfix, hacktoberfest

#1066 Add negate to match_mark
  lib/puppet/type/firewall.rb
  spec/acceptance/firewall_attributes_exceptions_spec.rb
Labels: community

#1079 (CONT-173) - Updating deprecated facter instances
  lib/facter/ip6tables_version.rb
  lib/facter/iptables_persistent_version.rb
  lib/facter/iptables_version.rb
  spec/unit/facter/iptables_persistent_version_spec.rb
  spec/unit/facter/iptables_spec.rb
Labels: bugfix, hacktoberfest
