Repository puppetlabs/puppetlabs-firewall, pull requests merged in 2022-02, with the labels that each got.

#1027 pdksync - (IAC-1787) Remove Support for CentOS 6
  metadata.json
Labels: bugfix

#1030 (SEC-944) Handle duplicate system rules
  README.md
  lib/puppet/provider/firewall/iptables.rb
  lib/puppet/type/firewall.rb
  spec/acceptance/firewall_duplicate_comment_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: feature

#1032 Release prep v3.4.0
  CHANGELOG.md
  metadata.json
Labels: maintenance
