Repository puppetlabs/puppetlabs-firewall, pull requests merged in 2023-08, with the labels that each got.

#1147 pdksync - (CAT-343) Audit modules and tools for references to travis. Removed all needless references to travis.
  README.md
  provision.yaml
Labels: maintenance

#1145 (DO NOT MERGE)(CAT-376) Rework firewall module to use the resource_api
  .devcontainer/devcontainer.json
  .rubocop.yml
  .rubocop_todo.yml
  .sync.yml
  Gemfile
  README.md
  REFERENCE.md
  lib/puppet/provider/firewall.rb
  lib/puppet/provider/firewall/firewall.rb
  lib/puppet/provider/firewall/ip6tables.rb
  lib/puppet/provider/firewall/iptables.rb
  lib/puppet/provider/firewallchain/firewallchain.rb
  lib/puppet/provider/firewallchain/iptables_chain.rb
  lib/puppet/type/firewall.rb
  lib/puppet/type/firewallchain.rb
  lib/puppet/util/firewall.rb
  lib/puppet_x/puppetlabs/firewall/ipcidr.rb
  lib/puppet_x/puppetlabs/firewall/utility.rb
  manifests/linux/redhat.pp
  spec/acceptance/class_spec.rb
  spec/acceptance/firewall_attributes_exceptions_spec.rb
  spec/acceptance/firewall_attributes_happy_path_spec.rb
  spec/acceptance/firewall_attributes_ipv6_exceptions_spec.rb
  spec/acceptance/firewall_attributes_ipv6_happy_path_spec.rb
  spec/acceptance/firewall_duplicate_comment_spec.rb
  spec/acceptance/firewallchain_spec.rb
  spec/acceptance/resource_cmd_spec.rb
  spec/acceptance/rules_spec.rb
  spec/acceptance/standard_usage_spec.rb
  spec/spec_helper_acceptance_local.rb
  spec/unit/puppet/provider/firewall/firewall_private_get_spec.rb
  spec/unit/puppet/provider/firewall/firewall_private_set_spec.rb
  spec/unit/puppet/provider/firewall/firewall_public_spec.rb
  spec/unit/puppet/provider/firewallchain/firewallchain_spec.rb
  spec/unit/puppet/provider/ip6tables_spec.rb
  spec/unit/puppet/provider/iptables_chain_spec.rb
  spec/unit/puppet/provider/iptables_spec.rb
  spec/unit/puppet/type/firewall_spec.rb
  spec/unit/puppet/type/firewallchain_spec.rb
  spec/unit/puppet/util/firewall_spec.rb
  spec/unit/puppet_x/puppetlabs/firewall/ipcidr_spec.rb
  spec/unit/puppet_x/puppetlabs/firewall/utility_spec.rb
Labels: backwards-incompatible

#1149 (RUBOCOP) Resolve Rubocop Issues
  .rubocop_todo.yml
  spec/acceptance/firewall_attributes_exceptions_spec.rb
  spec/spec_helper.rb
  spec/spec_helper_acceptance_local.rb
  spec/spec_helper_local.rb
  spec/unit/classes/firewall_linux_archlinux_spec.rb
  spec/unit/classes/firewall_linux_debian_spec.rb
  spec/unit/classes/firewall_linux_redhat_spec.rb
  spec/unit/classes/firewall_linux_spec.rb
  spec/unit/classes/firewall_spec.rb
  spec/unit/facter/iptables_persistent_version_spec.rb
  spec/unit/facter/iptables_spec.rb
Labels: bugfix
