Repository puppetlabs/puppetlabs-firewall, pull requests merged in 2023-06, with the labels that each got.

#1135 pdksync - (MAINT) - Allow Stdlib 9.x
  manifests/linux/debian.pp
  manifests/linux/redhat.pp
  metadata.json
Labels: feature

#1104 Force firewall chain delete
  README.md
  lib/puppet/provider/firewallchain/iptables_chain.rb
Labels: bugfix, community

#1123 Fix SELinux context on newer CentOS
  manifests/linux/redhat.pp
Labels: bugfix, community

#1126 Add support for parsing and using --tcp-option
  .rubocop.yml
  .rubocop_todo.yml
  lib/puppet/provider/firewall/ip6tables.rb
  lib/puppet/provider/firewall/iptables.rb
  lib/puppet/type/firewall.rb
  metadata.json
  spec/fixtures/ip6tables/conversion_hash.rb
  spec/fixtures/iptables/conversion_hash.rb
  spec/unit/puppet/provider/ip6tables_spec.rb
  spec/unit/puppet/provider/iptables_spec.rb
Labels: community

#1134 Change ip6tables_version to constant in provider.
  lib/puppet/provider/firewall/ip6tables.rb
  spec/unit/puppet/provider/ip6tables_spec.rb
Labels: community
