Repository puppetlabs/puppetlabs-firewall, pull requests merged in 2023-09, with the labels that each got.

#1150 pdksync - (CAT-1366) - Fix issue url from old jira to github
  metadata.json
Labels: maintenance

#1151 (maint) Update all README.md mentions of `action` to `jump`
  README.md
Labels: bugfix

#1153 (maint) README typo fix
  README.md
Labels: maintenance

#1154 (maint) README.md typo fix
  README.md
Labels: maintenance

#1157 (GH-1156) Fix for jump/goto attributes
  lib/puppet/type/firewall.rb
Labels: bugfix

#1160 (GH-1158) Fix for `dport/sport/state/ctstate/ctstatus` comparisons
  lib/puppet/provider/firewall/firewall.rb
  spec/unit/puppet/provider/firewall/firewall_public_spec.rb
Labels: bugfix

#1163 [CAT-1425] : Removing RedHat/Scientific/OracleLinux 6
  spec/acceptance/firewall_attributes_exceptions_spec.rb
  spec/acceptance/firewall_attributes_ipv6_exceptions_spec.rb
  spec/acceptance/firewall_attributes_ipv6_happy_path_spec.rb
  spec/acceptance/resource_cmd_spec.rb
  spec/spec_helper_acceptance_local.rb
  spec/unit/classes/firewall_linux_spec.rb
Labels: backwards-incompatible

#1165 (GH-1164) Only common jump values should be enforced as upcase
  lib/puppet/provider/firewall/firewall.rb
Labels: bugfix

#1166 Update issue link in ReadMe
  README.md
Labels: maintenance
