Repository puppetlabs/puppetlabs-firewall, pull requests merged in 2023-03, with the labels that each got.

#1110 (CONT-352) Syntax update
  .puppet-lint.rc
  .sync.yml
  Rakefile
  manifests/init.pp
  manifests/linux.pp
  manifests/linux/archlinux.pp
  manifests/linux/debian.pp
  manifests/linux/gentoo.pp
  manifests/linux/redhat.pp
  manifests/params.pp
  spec/spec_helper_local.rb
  spec/unit/classes/firewall_linux_archlinux_spec.rb
  spec/unit/classes/firewall_linux_debian_spec.rb
  spec/unit/classes/firewall_linux_redhat_spec.rb
  spec/unit/classes/firewall_linux_spec.rb
Labels: feature

#1107 Ignore OpenBSD, similarly to FreeBSD
  manifests/init.pp
Labels: community

#1117 pdksync - CONT-826/main/pin_puppet_litmus
  Gemfile
Labels: maintenance

#1118 (Cont 779) Add Support for Puppet 8 / Drop Support for Puppet 6
  .fixtures.yml
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  Rakefile
  metadata.json
Labels: backwards-incompatible
