Repository puppetlabs/puppetlabs-firewall, pull requests merged in 2024-03, with the labels that each got.

#1195 fix typos in documentation
  README.md
  lib/puppet/type/firewall.rb
Labels: community

#1197 (CAT-1746) - Ubuntu ARM spec failure fixes
  spec/acceptance/resource_cmd_spec.rb
Labels: maintenance

#1201 (MODULES-11449) - Fix for IPv6 NAT chain
  lib/puppet/provider/firewallchain/firewallchain.rb
  spec/acceptance/firewallchain_spec.rb
  spec/unit/puppet/provider/firewallchain/firewallchain_spec.rb
Labels: bugfix
